services:
  app:
    image: 'mauriceboe/trek:3.0.8'
    container_name: trek
    read_only: true
    security_opt:
      - 'no-new-privileges:true'
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
    tmpfs:
      - '/tmp:noexec,nosuid,size=64m'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - 'ENCRYPTION_KEY=${ENCRYPTION_KEY:-}'
      - 'TZ=${TZ:-UTC}'
      - 'LOG_LEVEL=${LOG_LEVEL:-info}'
      - 'ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-}'
    volumes:
      - './data:/app/data'
      - './uploads:/app/uploads'
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - wget
        - '-qO-'
        - 'http://localhost:3000/api/health'
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    labels:
      - coolify.managed=true
      - coolify.traefik.middlewares=authentik-auth@file,trek-security-headers@file,websocket-headers@file
      - traefik.enable=true
      - traefik.http.routers.https-0-ry6tx698p8c7bdjnj3cihhhs-app.rule=Host(`trek.aex.ovh`)
      - traefik.http.routers.https-0-ry6tx698p8c7bdjnj3cihhhs-app.entryPoints=https
      - traefik.http.routers.https-0-ry6tx698p8c7bdjnj3cihhhs-app.tls=true
      - traefik.http.routers.https-0-ry6tx698p8c7bdjnj3cihhhs-app.tls.certresolver=letsencrypt
      - traefik.http.routers.https-0-ry6tx698p8c7bdjnj3cihhhs-app.middlewares=gzip,authentik-auth@file
      - traefik.http.routers.https-0-ry6tx698p8c7bdjnj3cihhhs-app.service=https-0-ry6tx698p8c7bdjnj3cihhhs-app
      - traefik.http.services.https-0-ry6tx698p8c7bdjnj3cihhhs-app.loadbalancer.server.port=3000
      - traefik.http.routers.http-0-ry6tx698p8c7bdjnj3cihhhs-app.rule=Host(`trek.aex.ovh`)
      - traefik.http.routers.http-0-ry6tx698p8c7bdjnj3cihhhs-app.entryPoints=http
      - traefik.http.routers.http-0-ry6tx698p8c7bdjnj3cihhhs-app.middlewares=redirect-to-https
      - traefik.http.routers.http-0-ry6tx698p8c7bdjnj3cihhhs-app.service=http-0-ry6tx698p8c7bdjnj3cihhhs-app
      - traefik.http.services.http-0-ry6tx698p8c7bdjnj3cihhhs-app.loadbalancer.server.port=3000
